add sounds
Dima-Bulavenko/BattleCity pull request #49
Opened 2024-08-17 12:01 UTC by NontyD

2024-08-17 14:09 UTC, Dima-Bulavenko approved these changes

2024-08-17 14:21 UTC, Danut89 requested changes
![Screenshot 2024-08-17 003818](https://github.com/user-attachments/assets/90a92a0b-6804-47ea-8dab-ab399a684a8e)
Please if you can modify this wireframe, because the main menu is structured different now, i left you a screenshoot to see the menu how it should be in the wireframe.

2024-08-18 08:57 UTC, Danut89 approved these changes
i approved this guys and if we need to take out the wireframe which is not in line with the project

2024-08-18 09:14 UTC, Danut89 approved these changes

2024-08-18 09:14 UTC, closed without merging